services:
  ssh-645.cyrhades.fr:
    container_name: ssh-645
    build:
      context: ./.docker/ssh
      args:
        LANGUAGE: ${LANGUAGE:-fr}
    labels:
      ho.ctf.cyrhades: "challenge"
      ho.ctf.cyrhades.webssh: "1"
    environment:
      SSH_HOSTNAME: "ssh-645.cyrhades.fr"
      SSH_PORT: 22
      SSH_USERNAME: "cyrhades"
      SSH_PASSWORD: "secret"
    restart: unless-stopped
  little-d-big-trouble.cyrhades.fr:
    image: anssi/fcsc2026-crypto-little-d-big-trouble:latest
